DbName = 'Avior'
DbUrl = 'mongodb://192.168.178.75:27017'
DefaultClient = 'PHOENIX'
IgnoredClients = ['VDR-U', 'VDR-U-1', 'MMDG', 'VAVA', 'VDR']
Filetypes = [
  'ts',
  'mpg',
  'mkv'
]
IgnoredFiletypes = [
  'INFO.log'
]
MinAge = 0
